swagger: '2.0'
info:
  version: '1.0'
  title: april_poc
  x-lastModified: '08 May 2023 12:37:51 pm (India Standard Time)'
paths:
  /get/day:
    post:
      produces:
        - application/json
      responses:
        '200':
          description: Success response
      parameters:
        - name: hi
          in: header
          description: ''
          required: false
          type: string
          format: ''
      operationId: postGetDay
      description: hihi
      summary: hihi
